"""create job category and listing

Revision ID: 77c8a927798c
Revises: 
Create Date: 2026-01-24 18:40:12.626384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c8a927798c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'tag', 'label', name='uq_job_category_source_source_category_id')
    )
    op.create_table('job_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('minimum_salary', sa.Float(), nullable=True),
    sa.Column('maximum_salary', sa.Float(), nullable=True),
    sa.Column('job_post_url', sa.String(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('job_title', sa.Text(), nullable=False),
    sa.Column('job_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('company', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['job_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'job_id', name='uq_job_listing_source_job_id')
    )
    op.create_index(op.f('ix_job_listing_category_id'), 'job_listing', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_listing_category_id'), table_name='job_listing')
    op.drop_table('job_listing')
    op.drop_table('job_category')
    # ### end Alembic commands ###
